/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerCompra;
import Model.Compra;
import Model.MedicamentoNoRefrigerado;
import Model.MedicamentoRefrigerado;
import Model.Usuario;
import java.awt.Color;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Riarb
 */
public class ComprarMenu extends javax.swing.JFrame {
    private static Usuario usuarioActual;
    private ControllerCompra controller;
    private Map<String,MedicamentoNoRefrigerado> noRefrigerados;
    private Map<String,MedicamentoRefrigerado> refrigerados;
    private Map<String,Compra> listaCompra;
    /**
     * Creates new form ComprarMenu
     */
    public ComprarMenu(Usuario usuarioActual,Map<String,MedicamentoNoRefrigerado> noRefrigerados,Map<String,MedicamentoRefrigerado> refrigerados) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/logo.png")).getImage());
        this.setResizable(false);
        listaCompra = new LinkedHashMap<>();
        this.noRefrigerados = noRefrigerados;
        this.refrigerados = refrigerados;
        this.usuarioActual = usuarioActual;
        controller = new ControllerCompra(this, med,Spinner,table,this.noRefrigerados,this.refrigerados,listaCompra);
        controller.box();
        controller.tablaMenu();
    }

    public ComprarMenu(Usuario usuarioActual,Map<String, MedicamentoNoRefrigerado> noRefrigerados, Map<String, MedicamentoRefrigerado> refrigerados, Map<String, Compra> listaCompra) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/logo.png")).getImage());
        this.setResizable(false);
        this.usuarioActual = usuarioActual;
        this.noRefrigerados = noRefrigerados;
        this.refrigerados = refrigerados;
        this.listaCompra = listaCompra;
        controller = new ControllerCompra(this, med,Spinner,table,this.noRefrigerados,this.refrigerados,listaCompra);
        controller.box();
        controller.tablaMenu();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Volver = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        agregarButtom = new javax.swing.JPanel();
        ingresarLabel = new javax.swing.JLabel();
        verButtom = new javax.swing.JPanel();
        ingresarLabel1 = new javax.swing.JLabel();
        Spinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        med = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 153, 204));
        jPanel3.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU COMPRAR");

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/volver.png"))); // NOI18N
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Volver)
                        .addGap(33, 33, 33))))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carrito.png"))); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE", "PRECIO", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(table);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setText("MEDICAMENTO");

        agregarButtom.setBackground(new java.awt.Color(255, 153, 204));
        agregarButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarButtomMouseExited(evt);
            }
        });

        ingresarLabel.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        ingresarLabel.setForeground(new java.awt.Color(255, 255, 255));
        ingresarLabel.setText("AGREGAR");

        javax.swing.GroupLayout agregarButtomLayout = new javax.swing.GroupLayout(agregarButtom);
        agregarButtom.setLayout(agregarButtomLayout);
        agregarButtomLayout.setHorizontalGroup(
            agregarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarButtomLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(ingresarLabel)
                .addGap(36, 36, 36))
        );
        agregarButtomLayout.setVerticalGroup(
            agregarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarButtomLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ingresarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        verButtom.setBackground(new java.awt.Color(255, 153, 204));
        verButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verButtomMouseExited(evt);
            }
        });

        ingresarLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        ingresarLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ingresarLabel1.setText("VER ELEGIDO");

        javax.swing.GroupLayout verButtomLayout = new javax.swing.GroupLayout(verButtom);
        verButtom.setLayout(verButtomLayout);
        verButtomLayout.setHorizontalGroup(
            verButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verButtomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ingresarLabel1)
                .addGap(36, 36, 36))
        );
        verButtomLayout.setVerticalGroup(
            verButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verButtomLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ingresarLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setText("CANTIDAD ");

        med.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(agregarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(med, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(agregarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(verButtom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 710, 490));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/una ciudad minimalista en estilo de dibujo con color rosa en dimensiones de 150x150.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtomMouseClicked
        if(med.getSelectedItem()!="Selecciona el Medicamento" & (int)Spinner.getValue()>0){
            controller.buscarMedicamento();
            JOptionPane.showMessageDialog(null, "Medicamento agregado con exito", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            int valor =0;
            Spinner.setValue(valor);
            med.setSelectedIndex(0);
        } else if(med.getSelectedItem()=="Selecciona el Medicamento"){
            JOptionPane.showMessageDialog(null, "Debes seleccionar un medicamento para agregar.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }else if((int)Spinner.getValue()<=0){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una cantidad para agregar.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_agregarButtomMouseClicked

    private void agregarButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtomMouseEntered
        agregarButtom.setBackground(Color.pink);
    }//GEN-LAST:event_agregarButtomMouseEntered

    private void agregarButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarButtomMouseExited
        agregarButtom.setBackground(new Color(255, 153, 204));
    }//GEN-LAST:event_agregarButtomMouseExited

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        if(usuarioActual.isAcceso()){
            MainMenu main = new MainMenu(usuarioActual,noRefrigerados,refrigerados);
            main.setVisible(true);
            this.setVisible(false);
        }else if(!usuarioActual.isAcceso()){
            MainMenuCliente main = new MainMenuCliente(usuarioActual);
            main.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_VolverMouseClicked

    private void verButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verButtomMouseClicked
        if(!listaCompra.isEmpty()){
            Carrito car = new Carrito(usuarioActual,noRefrigerados,refrigerados,listaCompra);
            car.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar algun medicamento para procesar tu compra.", "ERROR", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_verButtomMouseClicked

    private void verButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verButtomMouseEntered
        verButtom.setBackground(Color.pink);
    }//GEN-LAST:event_verButtomMouseEntered

    private void verButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verButtomMouseExited
        verButtom.setBackground(new Color(255, 153, 204));
    }//GEN-LAST:event_verButtomMouseExited

    private void medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Map<String,MedicamentoNoRefrigerado> noRefrigerados = null;
        Map<String,MedicamentoRefrigerado> refrigerados =null;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarMenu(usuarioActual,noRefrigerados,refrigerados).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spinner;
    private javax.swing.JLabel Volver;
    private javax.swing.JPanel agregarButtom;
    private javax.swing.JLabel ingresarLabel;
    private javax.swing.JLabel ingresarLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> med;
    private javax.swing.JTable table;
    private javax.swing.JPanel verButtom;
    // End of variables declaration//GEN-END:variables
}
