/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Riarb
 */
public class crearMedicamento extends javax.swing.JFrame {

    /**
     * Creates new form crearMedicamento
     */
    public crearMedicamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        codigoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nombreLabel = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        loteLabel = new javax.swing.JLabel();
        loteTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        costoLabel = new javax.swing.JLabel();
        costoTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        unidadesLabel = new javax.swing.JLabel();
        unidadesTxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        codigoTxt = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        vigenciaLabel = new javax.swing.JLabel();
        userTxt7 = new javax.swing.JTextField();
        vigenciaBox = new javax.swing.JComboBox<>();
        guardarButtom = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 153, 204));
        jPanel3.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CREADOR DE MEDICAMENTOS");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/volver.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))))
        );

        nombreTxt.setBackground(new java.awt.Color(255, 204, 204));
        nombreTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        nombreTxt.setForeground(new java.awt.Color(153, 153, 153));
        nombreTxt.setText("Ingrese el nombre del medicamento");
        nombreTxt.setToolTipText("");
        nombreTxt.setBorder(null);
        nombreTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreTxtMousePressed(evt);
            }
        });
        nombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTxtActionPerformed(evt);
            }
        });

        codigoLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        codigoLabel.setText("CODIGO");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        nombreLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        nombreLabel.setText("NOMBRE");

        fechaTxt.setBackground(new java.awt.Color(255, 204, 204));
        fechaTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        fechaTxt.setForeground(new java.awt.Color(153, 153, 153));
        fechaTxt.setText("--/----");
        fechaTxt.setToolTipText("");
        fechaTxt.setBorder(null);
        fechaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaTxtMousePressed(evt);
            }
        });
        fechaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaTxtActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        loteLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        loteLabel.setText("LOTE");

        loteTxt.setBackground(new java.awt.Color(255, 204, 204));
        loteTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        loteTxt.setForeground(new java.awt.Color(153, 153, 153));
        loteTxt.setText("Ingrese el numero de lote");
        loteTxt.setToolTipText("");
        loteTxt.setBorder(null);
        loteTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loteTxtMousePressed(evt);
            }
        });
        loteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loteTxtActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        costoLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        costoLabel.setText("COSTO INICIAL");

        costoTxt.setBackground(new java.awt.Color(255, 204, 204));
        costoTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        costoTxt.setForeground(new java.awt.Color(153, 153, 153));
        costoTxt.setText("Ingrese el costo inicial");
        costoTxt.setToolTipText("");
        costoTxt.setBorder(null);
        costoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                costoTxtMousePressed(evt);
            }
        });
        costoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoTxtActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        unidadesLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        unidadesLabel.setText("UNIDADES EXISTENTES");

        unidadesTxt.setBackground(new java.awt.Color(255, 204, 204));
        unidadesTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        unidadesTxt.setForeground(new java.awt.Color(153, 153, 153));
        unidadesTxt.setText("Ingrese las unidades existentes");
        unidadesTxt.setToolTipText("");
        unidadesTxt.setBorder(null);
        unidadesTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unidadesTxtMousePressed(evt);
            }
        });
        unidadesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadesTxtActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        codigoTxt.setBackground(new java.awt.Color(255, 204, 204));
        codigoTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        codigoTxt.setForeground(new java.awt.Color(153, 153, 153));
        codigoTxt.setText("Ingrese el codigo del medicamento");
        codigoTxt.setToolTipText("");
        codigoTxt.setBorder(null);
        codigoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codigoTxtMousePressed(evt);
            }
        });
        codigoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTxtActionPerformed(evt);
            }
        });

        fechaLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        fechaLabel.setText("FECHA DE VENCIMIENTO");

        vigenciaLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        vigenciaLabel.setText("VIGENCIA");

        userTxt7.setBackground(new java.awt.Color(255, 204, 204));
        userTxt7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        userTxt7.setForeground(new java.awt.Color(153, 153, 153));
        userTxt7.setToolTipText("");
        userTxt7.setBorder(null);
        userTxt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxt7MousePressed(evt);
            }
        });
        userTxt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxt7ActionPerformed(evt);
            }
        });

        vigenciaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vigenciaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vigenciaBoxActionPerformed(evt);
            }
        });

        guardarButtom.setBackground(new java.awt.Color(255, 153, 204));
        guardarButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarButtomMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("GUARDAR");

        javax.swing.GroupLayout guardarButtomLayout = new javax.swing.GroupLayout(guardarButtom);
        guardarButtom.setLayout(guardarButtomLayout);
        guardarButtomLayout.setHorizontalGroup(
            guardarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardarButtomLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guardarButtomLayout.setVerticalGroup(
            guardarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guardarButtomLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadesTxt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unidadesLabel)
                            .addComponent(costoLabel)
                            .addComponent(loteLabel)
                            .addComponent(loteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoLabel)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(costoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vigenciaLabel)
                                .addGap(18, 18, 18)
                                .addComponent(userTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fechaLabel)
                            .addComponent(fechaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vigenciaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(guardarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(fechaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLabel)
                            .addComponent(vigenciaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vigenciaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(unidadesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidadesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 690, 490));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/una ciudad minimalista en estilo de dibujo con color rosa en dimensiones de 150x150.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTxtMousePressed
        if (nombreTxt.getText().equals("Ingrese el nombre del medicamento")){
            nombreTxt.setText("");
            nombreTxt.setForeground(Color.black);
        }
        if (codigoTxt.getText().isEmpty()){
            codigoTxt.setText("Ingrese el codigo del medicamento");
            codigoTxt.setForeground(new Color(153,153,153));
        }
        if (loteTxt.getText().isEmpty()){
            loteTxt.setText("Ingrese el numero de lote");
            loteTxt.setForeground(new Color(153,153,153));
        }
        if (costoTxt.getText().isEmpty()){
            costoTxt.setText("Ingrese el costo inicial");
            costoTxt.setForeground(new Color(153,153,153));
        }
        if (unidadesTxt.getText().isEmpty()){
            unidadesTxt.setText("Ingrese las unidades existentes");
            unidadesTxt.setForeground(new Color(153,153,153));
        }
        if (fechaTxt.getText().isEmpty()){
            fechaTxt.setText("--/----");
            fechaTxt.setForeground(new Color(153,153,153));
        }
        

    }//GEN-LAST:event_nombreTxtMousePressed

    private void nombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTxtActionPerformed

    private void fechaTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaTxtMousePressed
        if (fechaTxt.getText().equals("--/----")){
            fechaTxt.setText("");
            fechaTxt.setForeground(Color.black);
        }
        if (codigoTxt.getText().isEmpty()){
            codigoTxt.setText("Ingrese el codigo del medicamento");
            codigoTxt.setForeground(new Color(153,153,153));
        }
        if (nombreTxt.getText().isEmpty()){
            nombreTxt.setText("Ingrese el nombre del medicamento");
            nombreTxt.setForeground(new Color(153,153,153));
        }
        if (costoTxt.getText().isEmpty()){
            costoTxt.setText("Ingrese el costo inicial");
            costoTxt.setForeground(new Color(153,153,153));
        }
        if (unidadesTxt.getText().isEmpty()){
            unidadesTxt.setText("Ingrese las unidades existentes");
            unidadesTxt.setForeground(new Color(153,153,153));
        }
        if (loteTxt.getText().isEmpty()){
            loteTxt.setText("Ingrese el numero de lote");
            loteTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_fechaTxtMousePressed

    private void fechaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTxtActionPerformed

    private void loteTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loteTxtMousePressed
        if (loteTxt.getText().equals("Ingrese el numero de lote")){
            loteTxt.setText("");
            loteTxt.setForeground(Color.black);
        }
        if (codigoTxt.getText().isEmpty()){
            codigoTxt.setText("Ingrese el codigo del medicamento");
            codigoTxt.setForeground(new Color(153,153,153));
        }
        if (nombreTxt.getText().isEmpty()){
            nombreTxt.setText("Ingrese el nombre del medicamento");
            nombreTxt.setForeground(new Color(153,153,153));
        }
        if (costoTxt.getText().isEmpty()){
            costoTxt.setText("Ingrese el costo inicial");
            costoTxt.setForeground(new Color(153,153,153));
        }
        if (unidadesTxt.getText().isEmpty()){
            unidadesTxt.setText("Ingrese las unidades existentes");
            unidadesTxt.setForeground(new Color(153,153,153));
        }
        if (fechaTxt.getText().isEmpty()){
            fechaTxt.setText("--/----");
            fechaTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_loteTxtMousePressed

    private void loteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loteTxtActionPerformed

    private void costoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_costoTxtMousePressed
        if (costoTxt.getText().equals("Ingrese el costo inicial")){
            costoTxt.setText("");
            costoTxt.setForeground(Color.black);
        }
        if (codigoTxt.getText().isEmpty()){
            codigoTxt.setText("Ingrese el codigo del medicamento");
            codigoTxt.setForeground(new Color(153,153,153));
        }
        if (nombreTxt.getText().isEmpty()){
            nombreTxt.setText("Ingrese el nombre del medicamento");
            nombreTxt.setForeground(new Color(153,153,153));
        }
        if (loteTxt.getText().isEmpty()){
            loteTxt.setText("Ingrese el numero de lote");
            loteTxt.setForeground(new Color(153,153,153));
        }
        if (unidadesTxt.getText().isEmpty()){
            unidadesTxt.setText("Ingrese las unidades existentes");
            unidadesTxt.setForeground(new Color(153,153,153));
        }
        if (fechaTxt.getText().isEmpty()){
            fechaTxt.setText("--/----");
            fechaTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_costoTxtMousePressed

    private void costoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoTxtActionPerformed

    private void unidadesTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidadesTxtMousePressed
        if (unidadesTxt.getText().equals("Ingrese las unidades existentes")){
            unidadesTxt.setText("");
            unidadesTxt.setForeground(Color.black);
        }
        if (codigoTxt.getText().isEmpty()){
            codigoTxt.setText("Ingrese el codigo del medicamento");
            codigoTxt.setForeground(new Color(153,153,153));
        }
        if (nombreTxt.getText().isEmpty()){
            nombreTxt.setText("Ingrese el nombre del medicamento");
            nombreTxt.setForeground(new Color(153,153,153));
        }
        if (loteTxt.getText().isEmpty()){
            loteTxt.setText("Ingrese el numero de lote");
            loteTxt.setForeground(new Color(153,153,153));
        }
        if (costoTxt.getText().isEmpty()){
            costoTxt.setText("Ingrese el costo inicial");
            costoTxt.setForeground(new Color(153,153,153));
        }
        if (fechaTxt.getText().isEmpty()){
            fechaTxt.setText("--/----");
            fechaTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_unidadesTxtMousePressed

    private void unidadesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadesTxtActionPerformed

    private void codigoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoTxtMousePressed
        if (codigoTxt.getText().equals("Ingrese el codigo del medicamento")){
            codigoTxt.setText("");
            codigoTxt.setForeground(Color.black);
        }
        if (nombreTxt.getText().isEmpty()){
            nombreTxt.setText("Ingrese el nombre del medicamento");
            nombreTxt.setForeground(new Color(153,153,153));
        }
        if (loteTxt.getText().isEmpty()){
            loteTxt.setText("Ingrese el numero de lote");
            loteTxt.setForeground(new Color(153,153,153));
        }
        if (costoTxt.getText().isEmpty()){
            costoTxt.setText("Ingrese el costo inicial");
            costoTxt.setForeground(new Color(153,153,153));
        }
        if (unidadesTxt.getText().isEmpty()){
            unidadesTxt.setText("Ingrese las unidades existentes");
            unidadesTxt.setForeground(new Color(153,153,153));
        }
        if (fechaTxt.getText().isEmpty()){
            fechaTxt.setText("--/----");
            fechaTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_codigoTxtMousePressed

    private void codigoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTxtActionPerformed

    private void userTxt7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxt7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt7MousePressed

    private void userTxt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxt7ActionPerformed

    private void guardarButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseClicked
        int option = JOptionPane.showConfirmDialog( null, "REQUIERE REFRIGERACION?", "CREAR MEDICAMENTO", JOptionPane.YES_NO_OPTION );
        if (option == JOptionPane.YES_OPTION) { 
            Refrigerado ref = new Refrigerado();
            ref.setVisible(true);
            this.setVisible(false);
            
        } else if (option == JOptionPane.NO_OPTION) {
            NoRefrigerado ref = new NoRefrigerado();
            ref.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_guardarButtomMouseClicked

    private void guardarButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseEntered
        guardarButtom.setBackground(Color.pink);
    }//GEN-LAST:event_guardarButtomMouseEntered

    private void guardarButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseExited
        guardarButtom.setBackground(new Color(255, 153, 204));
    }//GEN-LAST:event_guardarButtomMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Gestor ventana = new Gestor();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void vigenciaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vigenciaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vigenciaBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JLabel costoLabel;
    private javax.swing.JTextField costoTxt;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JPanel guardarButtom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel loteLabel;
    private javax.swing.JTextField loteTxt;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel unidadesLabel;
    private javax.swing.JTextField unidadesTxt;
    private javax.swing.JTextField userTxt7;
    private javax.swing.JComboBox<String> vigenciaBox;
    private javax.swing.JLabel vigenciaLabel;
    // End of variables declaration//GEN-END:variables
}
