/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerRefrigeratedMedicines;
import Model.MedicamentoNoRefrigerado;
import Model.MedicamentoRefrigerado;
import Model.Usuario;
import java.awt.Color;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Riarb
 */
public class Refrigerado extends javax.swing.JFrame {
    private static Usuario usuarioActual;
    private static MedicamentoRefrigerado medicamento;
    private Map<String,MedicamentoNoRefrigerado> noRefrigerados;
    private Map<String,MedicamentoRefrigerado> refrigerados;
    private ControllerRefrigeratedMedicines controller;
    /**
     * Creates new form Refrigerado
     */
    public Refrigerado(Usuario usuarioActual,MedicamentoRefrigerado medicamento,
            Map<String,MedicamentoNoRefrigerado> noRefrigerados,Map<String,MedicamentoRefrigerado> refrigerados) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Images/logo.png")).getImage());
        this.setResizable(false);
        this.noRefrigerados = noRefrigerados;
        this.refrigerados = refrigerados;
        this.usuarioActual = usuarioActual;
        this.medicamento = medicamento;
        controller = new ControllerRefrigeratedMedicines(abierto,expuesto,temMax,temMin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        temperaturaMaxLabel = new javax.swing.JLabel();
        temperaturaMinLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        abierto = new javax.swing.JTextField();
        tiempoLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        expuesto = new javax.swing.JTextField();
        expuestoLabel = new javax.swing.JLabel();
        guardarButtom = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        temMax = new javax.swing.JComboBox<>();
        temMin = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 153, 204));
        jPanel3.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MEDICAMENTO REFRIGERADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        temperaturaMaxLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        temperaturaMaxLabel.setText("TEMPERATURA MAXIMA EN GRADOS");

        temperaturaMinLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        temperaturaMinLabel.setText("TEMPERATURA MINIMA EN GRADOS");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        abierto.setBackground(new java.awt.Color(255, 204, 204));
        abierto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        abierto.setForeground(new java.awt.Color(153, 153, 153));
        abierto.setText("Ingrese la cantidad de tiempo que puede estar abierto el medicamento");
        abierto.setToolTipText("");
        abierto.setBorder(null);
        abierto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abiertoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abiertoMousePressed(evt);
            }
        });
        abierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abiertoActionPerformed(evt);
            }
        });

        tiempoLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tiempoLabel.setText("TIEMPO ABIERTO");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        expuesto.setBackground(new java.awt.Color(255, 204, 204));
        expuesto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        expuesto.setForeground(new java.awt.Color(153, 153, 153));
        expuesto.setText("Ingrese la cantidad de tiempo que puede estar expuesto");
        expuesto.setToolTipText("");
        expuesto.setBorder(null);
        expuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                expuestoMousePressed(evt);
            }
        });
        expuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expuestoActionPerformed(evt);
            }
        });

        expuestoLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        expuestoLabel.setText("TIEMPO EXPUESTO");

        guardarButtom.setBackground(new java.awt.Color(255, 153, 204));
        guardarButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarButtomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarButtomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarButtomMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("GUARDAR");

        javax.swing.GroupLayout guardarButtomLayout = new javax.swing.GroupLayout(guardarButtom);
        guardarButtom.setLayout(guardarButtomLayout);
        guardarButtomLayout.setHorizontalGroup(
            guardarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardarButtomLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guardarButtomLayout.setVerticalGroup(
            guardarButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guardarButtomLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        temMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        temMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator4)
                        .addComponent(expuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(expuestoLabel)
                        .addComponent(abierto)
                        .addComponent(tiempoLabel)
                        .addComponent(temperaturaMinLabel)
                        .addComponent(temperaturaMaxLabel)
                        .addComponent(jSeparator3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(temperaturaMaxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(temperaturaMinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(tiempoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expuestoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(guardarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 650, 490));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/una ciudad minimalista en estilo de dibujo con color rosa en dimensiones de 150x150.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abiertoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abiertoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_abiertoMousePressed

    private void abiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abiertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abiertoActionPerformed

    private void expuestoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expuestoMousePressed
        if (expuesto.getText().equals("Ingrese la cantidad de tiempo que puede estar expuesto")){
            expuesto.setText("");
            expuesto.setForeground(Color.black);
        }
        
        if (abierto.getText().isEmpty()){
            abierto.setText("Ingrese la cantidad de tiempo que puede estar abierto el medicamento");
            abierto.setForeground(Color.gray);
        }
    }//GEN-LAST:event_expuestoMousePressed

    private void expuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expuestoActionPerformed

    private void guardarButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseClicked
        if(temMax.getSelectedItem()=="---"){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una temperatura maxima.");
        }else if(temMin.getSelectedItem()=="---"){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una temperatura minima.");
        }else if("Ingrese la cantidad de tiempo que puede estar abierto el medicamento".equals(abierto.getText()) || "".equals(abierto.getText())){
            JOptionPane.showMessageDialog(null, "Debes ingresar un tiempo abierto limite.");
        }else if("Ingrese la cantidad de tiempo que puede estar expuesto".equals(expuesto.getText())||"".equals(expuesto.getText())){
            JOptionPane.showMessageDialog(null, "Debes ingresar un tiempo expuesto limite.");
        }else{
            medicamento.setTemperaturaMaxima((Double.parseDouble((String) temMax.getSelectedItem())));
            medicamento.setTemperaturaMinima((Double.parseDouble((String) temMin.getSelectedItem())));
            medicamento.setTiempoAbierto(abierto.getText());
            medicamento.setTiempoExpuesto(expuesto.getText());
            refrigerados.put(medicamento.getNombreMedicamento(),medicamento);
            controller.guardarEnDB(medicamento);
            JOptionPane.showMessageDialog(null, "El medicamento se ha registrado de manera exitosa", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            Gestor ventana = new Gestor(usuarioActual,noRefrigerados,refrigerados);
            ventana.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_guardarButtomMouseClicked

    private void guardarButtomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseEntered
        guardarButtom.setBackground(Color.pink);
    }//GEN-LAST:event_guardarButtomMouseEntered

    private void guardarButtomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarButtomMouseExited
        guardarButtom.setBackground(new Color(255, 153, 204));
    }//GEN-LAST:event_guardarButtomMouseExited

    private void abiertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abiertoMouseClicked
        if (abierto.getText().equals("Ingrese la cantidad de tiempo que puede estar abierto el medicamento")){
            abierto.setText("");
            abierto.setForeground(Color.black);
        }

        if (expuesto.getText().isEmpty()){
            expuesto.setText("Ingrese la cantidad de tiempo que puede estar expuesto");
            expuesto.setForeground(Color.gray);
        }
    }//GEN-LAST:event_abiertoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Refrigerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Refrigerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Refrigerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Refrigerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Map<String,MedicamentoNoRefrigerado> noRefrigerados = null;
        Map<String,MedicamentoRefrigerado> refrigerados =null;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Refrigerado(usuarioActual,medicamento,noRefrigerados,refrigerados).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abierto;
    private javax.swing.JTextField expuesto;
    private javax.swing.JLabel expuestoLabel;
    private javax.swing.JPanel guardarButtom;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> temMax;
    private javax.swing.JComboBox<String> temMin;
    private javax.swing.JLabel temperaturaMaxLabel;
    private javax.swing.JLabel temperaturaMinLabel;
    private javax.swing.JLabel tiempoLabel;
    // End of variables declaration//GEN-END:variables
}
